### ISSUE TITLE
Support secrets stored in Hashicorp Vault

### ISSUE THREAD

**Issue by audip** [pusher/wave#28]
At Under Armour, we run Vault to store our secrets (like many other companies do), do you envision having an integration with a tool like Vault where a secret update in vault triggers a rolling update of deployment?

I’d be happy to contribute to the project if you think Wave can watch secrets in Vault. Let me know what your thoughts on this are and how you think this can be implemented to add value to the Wave project.

**Comment by gargath** [comment]
I'd be interested in knowing more about your use case.
How do you integrate Vault-based secret with Deployments?

Most solutions I know will use a separate controller to create Kubernetes Secret objects from Vault secrets which in turn then get referenced in Pod specs.
In such a scenario, I would expect that controller to ensure the Kubernetes Secrets stay in sync with Vault and Wave would work out of the box because it reacts to changes in the Kubernetes Secrets.

**Comment by audip** [comment]
Closing this out as https://github.com/DaspawnW/vault-crd fit our use-case really well
